GET http://localhost:8899/api/auth/
###

GET http://localhost:8899/api/post/
###

POST http://localhost:8899/api/auth/login
content-type: application/json

{
    "identity" : "andy@cc21.web",
    "password" : "a1234"
}
###
